### ISSUE TITLE
Certificate Issue

### ISSUE THREAD

**Issue by ssrira0** [ToolboxHub/ToolboxToolbox#110]
`Error: "fshift" had status -1, message "Could not establish a secure connection to "https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/7886/versions/5/download/zip". The reason is "error setting certificate verify locations:
`
I was trying to setup the transparentTrack toolbox, but when I ran the toolbox, it ran into this issue.

**Comment by gkaguirre** [comment]
This step of the configuration attempts to download the linked file from Matlab central. The error message suggests to me that this download was refused by the Matlab central website. Please try using a browser to visit the link you posted in the error message, and then download the file. It would be helpful to know if this works for you, or if this attempt also generates an error message.

**Comment by ssrira0** [comment]
> This step of the configuration attempts to download the linked file from Matlab central. The error message suggests to me that t

Thank you for your reply! So, I must clarify that the issue is occurring under an HPC environment, not my local computer. When I run it locally, it runs fine! The problem occurred after I changed from using  MATLAB 2018a to anything more recent (>2019a). There seems to be an issue with the `webget` command that is being passed through the `tbUse` function for the toolbox which the HPC environment cannot handle for some reason. If I run the pipeline through 2018, both `fshift` and `gif` are properly passed, and they exist within the /matlabcentral/ directory. The pipeline crashes soon after due to some of the functions within transparentTrack are from more recent versions of MATLAB. However, these installs of `fshift` and `gif` require a certificate check that occurs every time that `tbUse('transparentTrack')` is run, and it is not able to do so in an HPC environment.

**Comment by wwarriner** [comment]
Hi, I'm assisting @ssrira0 on the issue with our HPC environment. We've boiled the issue down to a problem with `websave()` using R2018b and later on our cluster.

The full error looks like:
```
>> websave("test.zip", "https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/7886/versions/5/download/zip");
Error using websave (line 98)
Secure connection to "https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/7886/versions/5/download/zip" not established because "error setting
certificate verify locations:
CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: none". Check your system certificates for expired, missing, or invalid certificates.
```

I've contacted MATLAB support and the suggestions they've made to fix the issue are to either create a symlink from the standard ssl certificate location `/etc/ssl/certs/ca-certificates.crt` to `/etc/pki/tls/certs/ca-bundle.crt`, which our users are not able to do. We are looking into this solution for our cluster.

The alternative is to do something like the following using `weboptions()`
```
>> webread('https://www.google.com';, weboptions('Certificate', '/etc/ssl/certs/ca-certificates.crt')) 
```
There does not appear to be a way to pass this information through TbTb. Is it possible to do this currently? Or is this something that could be added as a feature?

**Comment by gkaguirre** [comment]
The fshift function is used only in a fairly esoteric aspect of transparentTrack (shifting the temporal relationship between a measure of brain position and the measure of eye position).

Unless you are trying to use this functionality, for now I suggest that you press ahead with your analysis, ignoring the warning about fshift.

In the meantime, we can investigate if there is a fix for this webget error. It would be especially helpful if you are able to identify a fix on your end that we could then incorporate into the TbTb code.

Geoff



> On Mar 25, 2021, at 1:18 PM, William Warriner ***@***.***> wrote:
> 
> 
> Hi, I'm assisting @ssrira0 on the issue with our HPC environment. We've boiled the issue down to a problem with websave() using R2018b and later on our cluster.
> 
> The full error looks like:
> 
> >> websave("test.zip", "https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/7886/versions/5/download/zip");
> Error using websave (line 98)
> Secure connection to "https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/7886/versions/5/download/zip" not established because "error setting
> certificate verify locations:
> CAfile: /etc/ssl/certs/ca-certificates.crt
> CApath: none". Check your system certificates for expired, missing, or invalid certificates.
> 
> I've contacted MATLAB support and the suggestions they've made to fix the issue are to either create a symlink from the standard ssl certificate location /etc/ssl/certs/ca-certificates.crt to /etc/pki/tls/certs/ca-bundle.crt, which our users are not able to do. We are looking into this solution for our cluster.
> 
> The alternative is to do something like the following using weboptions()
> 
> >> webread('https://www.google.com';, weboptions('Certificate', '/etc/ssl/certs/ca-certificates.crt')) 
> 
> There does not appear to be a way to pass this information through TbTb. Is it possible to do this currently? Or is this something that could be added as a feature?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--

Geoffrey Karl Aguirre, M.D., Ph.D.
http://gkaguirre.com
Associate Professor of Neurology
University of Pennsylvania
Philadelphia, PA

**Comment by ssrira0** [comment]
The aspect that I am trying to get to work on currently is obtaining the scene geometry. I tried working around it by ignoring `fshift` as you suggested, but I am running into this error now where it seems to be calling on `fshift` through bads. I've attached the full error below:
`Unrecognized function or variable 'fshift'.

Error in sceneObj/updateHead>censorShift (line 76)
    vecOut(jj,:) = fshift(vecIn(jj,:),frameShift);

Error in sceneObj/updateHead (line 51)
B = (censorShift(A,xHead(1))'*rotMat(xHead(2),xHead(3),xHead(4))')';

Error in sceneObj/returnError (line 38)
obj.updateHead;

Error in multiSceneObjective (line 37)
    fValScene(ss) = sceneObjects{ss}.returnError(subX, errorArgs);

Error in
estimateSceneParams>@(x)multiSceneObjective(x,sceneObjects,model,strategy,ii,p.Results.errorArgs,verbose)
(line 397)
    myObjAll = @(x)
    multiSceneObjective(x,sceneObjects,model,strategy,ii,p.Results.errorArgs,verbose);

Error in bads>@(x)fun(expandvars(x,fixidx,fixedvars)) (line 369)
        fun_fix = @(x) fun(expandvars(x,fixidx,fixedvars));

Error in funlogger (line 96)
                fval = fun(x);

Error in evalinitmesh (line 31)
    [yval,optimState] = funlogger(funwrapper,u0,optimState,'iter');

Error in bads (line 435)
    evalinitmesh(u0,funwrapper,optimState,options,prnt);

Error in fixedbads (line 39)
        x_free = bads(fun_fix,x0,LB,UB,PLB,PUB,nonbcon_fix,options);

Error in bads (line 394)
    [x,fval,exitflag,output,optimState,gpstruct] =
    fixedbads(fun_fix,x0,LB,UB,PLB,PUB,nonbcon_fix,options,fixidx,nargout);

Error in estimateSceneParams (line 404)
        x = bads(myObjAll,x,lb,ub,lbp,ubp,model.func.nonbcon,options);

Error in runVideoPipeline (line 310)
                    eval(funCalls{ff});'

**Comment by gkaguirre** [comment]
Gotcha. How about you write me an email and I can try and figure this out for you (aguirreg@upenn.edu)? The TbTb issue about webget is something we can figure out separately.

**Comment by DavidBrainard** [comment]
I added an option 'CertificateFilename','' to the web save command.  I think this causes later versions of Matlab to revert to the behavior of earlier versions, and not complain when there is an SSL cert issue.

This is on a new branch of ToolboxToolbox, selfie.  Can you try it in your HPC environment and see if it fixes the problem?  Let me know.

**Comment by ssrira0** [comment]
> I added an option 'CertificateFilename','' to the web save command. I think this causes later versions of Matlab to revert to the behavior of earlier versions, and not complain when there is an SSL cert issue.
> 
> This is on a new branch of ToolboxToolbox, selfie. Can you try it in your HPC environment and see if it fixes the problem? Let me know.

This seemed to have fixed this issue in my HPC environment! Thank you!

**Comment by DavidBrainard** [comment]
I folded this into the master branch so it should be there for you now.  Closing this issue.
