### ISSUE TITLE
A dot name structure assignment is illegal when the structure is empty.  Use a subscript on the structure.

### ISSUE THREAD

**Issue by spitschan** [ToolboxHub/ToolboxToolbox#17]
Setting up a TbTb configuration on a Linux cluster running MATLAB 8.4.0.150421 (R2014b). When running a TbTb config which otherwise works without any problems, I run into the following error message:

```
>> tbUse('MelanopsinMR_PupilAnalysisConfig')
Obtaining "ToolboxRegistry".
A dot name structure assignment is illegal when the structure is empty.  Use a subscript on the
structure.

Error in tbFetchToolboxes (line 36)
[results.operation] = deal('skipped');

Error in tbDeployToolboxes (line 157)
resolved = tbFetchToolboxes(resolved, ...

Error in tbUse (line 84)
results = tbDeployToolboxes( ...
 ```

I believe that this error message shows up from time to time. What's the fix?

**Comment by spitschan** [comment]
Some auxiliary information:

**MATLAB**
MATLAB version: R2014b (8.4.0.150421) 64-bit (glnxa64)

**Git**
```
>> !git --version
git version 1.7.1
```

**System**
```
$ uname -a
Linux chead.uphs.upenn.edu 2.6.32-504.16.2.el6.x86_64 #1 SMP Wed Apr 22 06:48:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by DavidBrainard** [comment]
This is probably another variant of a bug we fixed in some places, where 2015a and earlier behave differently when you try to assign a field to an empty struct.  We should be able to track this down and code around it, if we know the line number of the error.  Basically, we have to protect some code with an if ~isempty(....) and make sure that the result is handled OK in the new case.

**Comment by spitschan** [comment]
In that specific instance, `config`, which is passed to `tbFetchToolboxes` is empty:

```
K>> config

config = 

0x0 struct array with fields:

    flavor
    hook
    importance
    localHookTemplate
    name
    pathPlacement
    subfolder
    toolboxRoot
    type
    update
    url
```

The program that calls `tbFetchToolboxes` is called `tbDeployToolboxes`. In lines 144 following, the config is retrieved. Somehow the call to `TbIncludeStrategy.resolveIncludedConfigs(config, registry);` is not successful, and that's why the struct is empty:

```
K>> [resolved, included] = TbIncludeStrategy.resolveIncludedConfigs(config, registry);
K>> resolved

resolved = 

0x0 struct array with fields:

    flavor
    hook
    importance
    localHookTemplate
    name
    pathPlacement
    subfolder
    toolboxRoot
    type
    update
    url
```

I would suspect that what that function does breaks under older versions of MATLAB?

**Comment by DavidBrainard** [comment]
OK, @ben it looks like we need to do the same protection around resolved that we did around included.  Manuel says that the configuration works fine under 2016a on his computer.  I think when we looked at this, we thought resolved should never be empty, but I'm guessing there is a case where it is in fact OK for resolved to be empty.

I'm not going to make the change, though, since you are the expert!

**Comment by benjamin-heasly** [comment]
OK, cool.  So I guess this kind of `[foo.bar]` syntax is not safe across Matlab versions.

I went through and replaced this syntax with wrapper functions that do some error checking.  This is working for me in 2016a.

@spitschan -- Does it work now on the older versions?

**Comment by spitschan** [comment]
It throws no error but it also doesn't set up the toolboxes on the Linux system that I've been using:

```
>> tbUse('MelanopsinMR_BOLDAnalysisConfig')
Obtaining "ToolboxRegistry".
Adding "ToolboxToolbox" to path at "/home/mspitschan/matlab/ToolboxToolbox".
Looks good: all resolved toolboxes deployed OK.
Looks good: all included toolboxes deployed OK.

ans = 

0x0 struct array with fields:

    flavor
    hook
    importance
    localHookTemplate
    name
    pathPlacement
    subfolder
    toolboxRoot
    type
    update
    url
```

Compare that to what I get on OS X MATLAB R2015b:

```
>> tbUse('MelanopsinMR_BOLDAnalysisConfig')
Updating "ToolboxRegistry".
Updating "MRklar".
Updating "MRlyze".
Updating "mriTemporalFitting".
Adding "ToolboxToolbox" to path at "/Users/mspits/Documents/MATLAB/Toolboxes/ToolboxToolbox".
Adding "MRklar" to path at "/Users/mspits/Documents/MATLAB/Toolboxes/MRklar".
Adding "MRlyze" to path at "/Users/mspits/Documents/MATLAB/Toolboxes/MRlyze".
Adding "mriTemporalFitting" to path at "/Users/mspits/Documents/MATLAB/Toolboxes/mriTemporalFitting".
```

**Comment by benjamin-heasly** [comment]
I think we fixed this specific issue and moved on to other issues that you're facing.  Right?  Please re-open if I'm wrong about that.
