### ISSUE TITLE
Reset woes

### ISSUE THREAD

**Issue by DavidBrainard** [ToolboxHub/ToolboxToolbox#2]

**Comment by DavidBrainard** [comment]
When I do a reset and then add on a Matlab toolbox, I get an error.  This is, I think, because the order of the subfolders of the toolbox is not the same when they get put back as they were to begin with, and the wrong version of a function is shadowed.  Why Matlab would have two functions of the same name and count on the path order is beyond knowing, but apparently they do.  See the output of "which pca" before and after the tbUse call:

>> which pca
/Applications/MATLAB_R2016a.app/toolbox/stats/stats/pca.m
>> tbUse({'IBIOColorDetect'},'reset','none');
Updating "ToolboxRegistry".
Updating "signal".
Updating "stats".
Updating "images".
Updating "optim".
Updating "isetbio".
Updating "UnitTestToolbox".
Updating "RemoteDataToolbox".
Updating "BrainardLabToolbox".
Adding ToolboxToolbox to path at "/Users/Shared/Matlab/Toolboxes/ToolboxToolbox".
Adding "signal" to path at "/Applications/MATLAB_R2016a.app/toolbox/signal".
Adding "stats" to path at "/Applications/MATLAB_R2016a.app/toolbox/stats".
Adding "images" to path at "/Applications/MATLAB_R2016a.app/toolbox/images".
Adding "optim" to path at "/Applications/MATLAB_R2016a.app/toolbox/optim".
Adding "isetbio" to path at "/Users/Shared/Matlab/Toolboxes/isetbio".
Adding "UnitTestToolbox" to path at "/Users/Shared/Matlab/Toolboxes/UnitTestToolbox".
Adding "RemoteDataToolbox" to path at "/Users/Shared/Matlab/Toolboxes/RemoteDataToolbox".
Adding "BrainardLabToolbox" to path at "/Users/Shared/Matlab/Toolboxes/BrainardLabToolbox".
Running local hook for "isetbio": "~/localToolboxHooks/isetbio.m".
Running local hook for "IBIOColorDetect": "~/localToolboxHooks/IBIOColorDetect.m".
Looks good: all toolboxes deployed OK.
>> which pca
/Applications/MATLAB_R2016a.app/toolbox/stats/eml/pca.m
>>

**Comment by benjamin-heasly** [comment]
How annoying.

I did some testing on my machine.  I see that what Matlab does by default is different from what ToolboxToolbox does.

Here's an excerpt of what Matlab does with "images" toolbox by default.  The subfolders are almost but not quite grouped together, and almost but not quite in alphabetical order.
```
>> restoredefaultpath()
>> path()
	MATLABPATH
...
	/usr/local/MATLAB/R2016a/toolbox/images/colorspaces
	/usr/local/MATLAB/R2016a/toolbox/images/images
	/usr/local/MATLAB/R2016a/toolbox/images/imdata
	/usr/local/MATLAB/R2016a/toolbox/images/imuitools
	/usr/local/MATLAB/R2016a/toolbox/images/iptformats
	/usr/local/MATLAB/R2016a/toolbox/images/iptutils
...
	/usr/local/MATLAB/R2016a/toolbox/images/imdemos
...
```

And here's what ToolboxToolbox does, using `addpath(genpath())`.  The subfolders are grouped together and in alphabetical order.  There are some extra subfolders that Matlab didn't want.
```
	MATLABPATH
...
	/usr/local/MATLAB/R2016a/toolbox/images
	/usr/local/MATLAB/R2016a/toolbox/images/colorspaces
	/usr/local/MATLAB/R2016a/toolbox/images/colorspaces/eml
	/usr/local/MATLAB/R2016a/toolbox/images/icons
	/usr/local/MATLAB/R2016a/toolbox/images/images
	/usr/local/MATLAB/R2016a/toolbox/images/images/eml
	/usr/local/MATLAB/R2016a/toolbox/images/imdata
	/usr/local/MATLAB/R2016a/toolbox/images/imdemos
	/usr/local/MATLAB/R2016a/toolbox/images/imdemos/html
	/usr/local/MATLAB/R2016a/toolbox/images/imuitools
	/usr/local/MATLAB/R2016a/toolbox/images/iptformats
	/usr/local/MATLAB/R2016a/toolbox/images/iptutils
```

I think the `eml` folders are for "Embedded Matlab" and we're not supposed to have them on the path.  The functions in there look like alternative implementations of regular functions that have the same name.  So one thing we can do is exclude these folders.

We can also root around in `(matlab-root)/toolbox/local/path`.  I see files like `images.phl` that seem to list explicit path entries.  Maybe this is the way to get the exact toolbox path definitions that Matlab uses.

I'll look a little deeper.

**Comment by benjamin-heasly** [comment]
I think you will be good to go now.

I reimplemented the TbInstalledStrategy.  It no longer uses `addpath(genpath())` to put installed Matlab toolboxes on the path.

Now, it asks Matlab for the "official default" path using the built-in `restoredefaultpath()`.  For each specific installed toolbox that we want, it selects matching path entries from this official default path.  So what we finally add to the path will be a subset of Matlab's official default path, with toolbox subfolders in the same order.

Automated tests are passing.  Can you pull and try again?

**Comment by DavidBrainard** [comment]
Now I get a new error.  You can see the IBIOColorDetect file in the registry.

DB

>> tbUse({'IBIOColorDetect'},'reset','all');
Updating "ToolboxRegistry".
Updating "signal".
Updating "stats".
Updating "images".
Updating "optim".
Updating "isetbio".
Updating "UnitTestToolbox".
Updating "RemoteDataToolbox".
Updating "BrainardLabToolbox".
Resetting path for local toolboxes.
Warning: Duplicate directory name: /Applications/MATLAB_R2016a.app/toolbox/stateflow/stateflow
> In restoredefaultpath (line 52)
  In tbResetMatlabPath (line 38)
  In tbDeployToolboxes (line 127)
  In tbUse (line 51)
Adding ToolboxToolbox to path at "/Users/Shared/Matlab/Toolboxes/ToolboxToolbox".
Resetting path for installed Matlab toolboxes.
Warning: Support for ver('fixpoint') will be removed in a future release.  Use ver('fixedpoint') instead.
> In ver>locGetSingleToolboxInfo (line 279)
  In ver (line 52)
  In tbResetMatlabPath (line 73)
  In tbDeployToolboxes (line 127)
  In tbUse (line 51)
Adding "signal" to path at "/Applications/MATLAB_R2016a.app/toolbox/signal".
Adding "stats" to path at "/Applications/MATLAB_R2016a.app/toolbox/stats".
Adding "images" to path at "/Applications/MATLAB_R2016a.app/toolbox/images".
Adding "optim" to path at "/Applications/MATLAB_R2016a.app/toolbox/optim".
Adding "isetbio" to path at "/Users/Shared/Matlab/Toolboxes/isetbio".
Adding "UnitTestToolbox" to path at "/Users/Shared/Matlab/Toolboxes/UnitTestToolbox".
Adding "RemoteDataToolbox" to path at "/Users/Shared/Matlab/Toolboxes/RemoteDataToolbox".
Adding "BrainardLabToolbox" to path at "/Users/Shared/Matlab/Toolboxes/BrainardLabToolbox".
Running local hook for "isetbio": "~/localToolboxHooks/isetbio.m".
Running local hook for "IBIOColorDetect": "~/localToolboxHooks/IBIOColorDetect.m".
Error: "signal" had status -1, message "The class TbInstalledStrategy has no Constant property or Static method named 'defaultPathMatches'."
Error: "stats" had status -1, message "The class TbInstalledStrategy has no Constant property or Static method named 'defaultPathMatches'."
Error: "images" had status -1, message "The class TbInstalledStrategy has no Constant property or Static method named 'defaultPathMatches'."
Error: "optim" had status -1, message "The class TbInstalledStrategy has no Constant property or Static method named 'defaultPathMatches'."
Something went wrong, please see above.
>>

**Comment by benjamin-heasly** [comment]
Looks like the code is updated but Matlab doesn't know it.  Did you restart Matlab or `clear classes`?

`tbUse({'IBIOColorDetect'},'reset','all');` is working for me on my laptop and the GPC cluster.

**Comment by benjamin-heasly** [comment]
Since my last message I pushed more changes.  So in case we were racing, you might want to pull again.

**Comment by DavidBrainard** [comment]
Yes, seems to work now.  Some combination of pulling and restarting Matlab did the trick.

DB
