### ISSUE TITLE
ping test for internet fails behind firewall

### ISSUE THREAD

**Issue by gkaguirre** [ToolboxHub/ToolboxToolbox#23]
When connected to the internet from behind a corporate / university firewall, the ping command fails (apparently to avoid some vulnerability to probing pings).

Is there an alternative "checkInternetCommand" that could replace ping?

**Comment by benjamin-heasly** [comment]
Many commands could work as long as exit status indicates internet connectivity (ie 0 status <--> connected).

Two possibilities might be:
```
curl www.google.com
wget www.google.com
```

But it depends whether `curl` or `wget` is installed.

**Comment by gkaguirre** [comment]
Thanks. `curl` works behind the `uphs` firewall, for anyone else who had this problem
