### ISSUE TITLE
Don't check internet by default?

### ISSUE THREAD

**Issue by benjamin-heasly** [ToolboxHub/ToolboxToolbox#26]
Several users have had trouble with `tbCheckInternet()` returning false negatives.  This makes commands like `tbUse()` fail for no good reason.

In some cases the false negative might just be a timeout.  In other cases, it may be caused by local firewall settings and the like.

Should we disable checking for internet connectivity by default?  Or find a more robust way to check?

**Comment by gkaguirre** [comment]
I haven't had a reported connection failure since switching to `curl` as my check. Works fine behind the hospital firewall as well.

**Comment by benjamin-heasly** [comment]
Talking to DB --

How about, when the `tbCheckInternet()` command fails, print a message that says, "you seem to be offline, you might want to try again with internet checks turned off.  For example `tbUse( ... "checkInternet", false)`

And then, also add the `checkInternet` parameter for relevant functions.  This would allow us to use the internet check when it's working, and give an easy work-around when it's not.

**Comment by benjamin-heasly** [comment]
Closed by https://github.com/ToolboxHub/ToolboxToolbox/pull/41
