### ISSUE TITLE
tbUse and ping

### ISSUE THREAD

**Issue by bock42** [ToolboxHub/ToolboxToolbox#27]
I am having issues with `tbUse`, most likely related to a UPHS firewall. 

In Matlab:

```tbUse('sample-repo')``` 

results in the following message:

```
>> tbUse('sample-repo')
Updating "ToolboxRegistry".
Could not reach the internet.
  command: env -i /sbin/ping -c 1 www.google.com
  message: PING www.google.com (4.31.115.242): 56 data bytes

--- www.google.com ping statistics ---
1 packets transmitted, 0 packets received, 100.0% packet loss

Unable to fetch toolbox registry "ToolboxRegistry".
  command was: git pull.
  message was: PING www.google.com (4.31.115.242): 56 data bytes

--- www.google.com ping statistics ---
1 packets transmitted, 0 packets received, 100.0

ans =

     []
```

In terminal:

```ping www.google.com``` 

results in the following message:

```
PING www.google.com (4.31.115.242): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
...
```

I can confirm that using a non-UPHS internet connection has no issue, and I am able to replicate this on both my work desktop (ethernet connection) and my laptop (wifi with VPN).

**Comment by gkaguirre** [comment]
You can use `curl` behind the hospital firewall to avoid this problem. Configure your `startup.m` file with this entry:

`% system command used to check whether the Internet is reachable
if ispc()
    checkInternetCommand = 'curl www.google.com';
else
    checkInternetCommand = 'curl www.google.com';
end
setpref('ToolboxToolbox', 'checkInternetCommand', checkInternetCommand);`

**Comment by bock42** [comment]
Great, adding:

```checkInternetCommand = 'curl www.google.com';
setpref('ToolboxToolbox', 'checkInternetCommand', checkInternetCommand);```

to my `startup.m` file did the trick.  Thanks!
