### ISSUE TITLE
cd() to toolbox folder by name.

### ISSUE THREAD

**Issue by benjamin-heasly** [ToolboxHub/ToolboxToolbox#29]
It would be handy to be able to cd() to the folder that contains a toolbox, based on the name of the toolbox record.  This way, it would be possible to move among toolboxes without having to remember where the toolbox folder is located.

For example, to get to the ToolboxRegistry, I currently have to use this machine-dependent command:
```
cd /home/ben/toolboxes/ToolboxRegistry/
```

It would be nice instead to do:
```
tbCd ToolboxRegistry
```

**Comment by gkaguirre** [comment]
That would be nice

**Comment by benjamin-heasly** [comment]
In addition to `tbCd()`, it would be nice to have `tbLocateToolbox()`.  This would return the path to the toolbox, but not `cd()` to it.

Also, `tbLocateSelf()` to get the path where ToolboxToolbox is installed.
