### ISSUE TITLE
Error message we don't understand

### ISSUE THREAD

**Issue by DavidBrainard** [ToolboxHub/ToolboxToolbox#5]
Trying to use TbTb with OneLight.  We get the following error message.

>> tbUse('OneLight')
Updating "ToolboxRegistry".
Updating "BrainardLabToolbox".
Updating "Psychtoolbox-3".
Updating "OneLightDriver".
Updating "OneLightToolbox".
Updating "SilentSubstitutionToolbox".
Adding "ToolboxToolbox" to path at "/Users/Shared/Matlab/Toolboxes/ToolboxToolbox".
Adding "BrainardLabToolbox" to path at "/Users/Shared/Matlab/Toolboxes/BrainardLabToolbox".
Adding "Psychtoolbox-3" to path at "/Users/Shared/Matlab/Toolboxes/Psychtoolbox-3/Psychtoolbox".
Adding "OneLightDriver" to path at "/Users/Shared/Matlab/Toolboxes/OneLightDriver".
Adding "OneLightToolbox" to path at "/Users/Shared/Matlab/Toolboxes/OneLightToolbox".
Adding "SilentSubstitutionToolbox" to path at "/Users/Shared/Matlab/Toolboxes/SilentSubstitutionToolbox".
Adding "mgl" to path at "/Users/Shared/Matlab/Toolboxes/mgl".
Adding "PsychCalLocalData" to path at "/Users/Shared/Matlab/Toolboxes/PsychCalLocalData".
Error: "BrainardLabToolbox" had status 1, message "fatal: unable to access 'https://npcottaris@github.com/DavidBrainard/BrainardLabToolbox.git/': SSL certificate problem: unable to get local issuer certificate"
Error: "Psychtoolbox-3" had status 1, message "fatal: unable to access 'https://github.com/Psychtoolbox-3/Psychtoolbox-3.git/': SSL certificate problem: unable to get local issuer certificate"
Error: "OneLightDriver" had status 1, message "fatal: unable to access 'https://npcottaris@github.com/DavidBrainard/OneLightDriver.git/': SSL certificate problem: unable to get local issuer certificate"
Error: "OneLightToolbox" had status 1, message "fatal: unable to access 'https://npcottaris@github.com/DavidBrainard/OneLightToolbox.git/': SSL certificate problem: unable to get local issuer certificate"
Error: "SilentSubstitutionToolbox" had status 1, message "fatal: unable to access 'https://npcottaris@github.com/spitschan/SilentSubstitutionToolbox.git/': SSL certificate problem: unable to get local issuer certificate"
Something went wrong, please see above.

We don't know what it means. These toolboxes were already installed on the system.  Running git pull from the terminal or Tower works fine.

More generally, we are not sure how the TbTb interacts with what user has the toolbox checked out.

**Comment by benjamin-heasly** [comment]
I'm not sure I understand, either.

The ToolboxToolbox isn't trying to be all that fancy with Git commands.  I wonder if something about the Matlab environment is different.  Could you take a Git command that works in the terminal and try it through the `system()` command?

**Comment by DavidBrainard** [comment]
I think we're deep in version heck.  "git pull" appears to work fine in the terminal, but !git pull fails in Matlab, with an error message like the above.  The system we're running is Yosemite, because El Capitan will not talk to our radiometers.  We have verified that both terminal and Matlab are running the same version of git, which we just updated using Homebrew.

It may be that the best approach is for you to work directly with Manuel on this one, as he can sit at the computer while you Skype or some such.

**Comment by benjamin-heasly** [comment]
Thanks.  It's nice to know that the problem seems to be outside the toolbox toolbox -- at least from my POV.

My guess is that Matlab is the culprit, doing something unnatural with the shell environment for `!` or `system()`.  Maybe we need to clear or set some environment variables related SSL.

**Comment by benjamin-heasly** [comment]
This turned out the be an issue with the environment variables that Matlab sets for the `system()` command.  The fix for ToolboxToolbox was to be defensive when running commands, and clear the environment first.
