### ISSUE TITLE
Team Review of v0.2

### ISSUE THREAD

**Issue by benjamin-heasly** [ToolboxHub/ToolboxToolbox#50]
Hi @DavidBrainard -- I've been merging changes for v0.2 unilaterally, so that I can keep moving and not worry about "dangling" pull requests.

But let's review some of the changes together before we declare victory over v0.2.  The issues with the label [not small](https://github.com/ToolboxHub/ToolboxToolbox/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3Av0.2%20label%3A%22not%20small%22%20) might benefit the most from reviewing together.

**Comment by DavidBrainard** [comment]
Reviewed.
