### ISSUE TITLE
Projects, little things

### ISSUE THREAD

**Issue by DavidBrainard** [ToolboxHub/ToolboxToolbox#52]
a) I was expecting tbUseProject to run the local hook for the project, but it doesn't.  I added some code at the end of tbUseProject to do this, but it is probably quite fragile.  Probably the right way is to call into the routines inside of tbDeployToolbox, but those are private to that file and I wasn't so ambitious as to break them out.

Maybe there is a different intended way to run a project local hook, but this seemed natural and the preferred default behavior, to be turned off with a key-value arg to tbUseProject if desired.

b) I am not sure whether tbUseProject does a pull on the project.  I am thinking it should be default as with toolboxes, and the update field of the json file can be used to customize.

c) I am unsure of the best way to put subfolders of a project on the path.  Currently I am doing this in the local hook, but perhaps it should be as a field in the json file?

d) I am ending up with a copy of the ToolboxRegistry inside my project. This might be because of the way my local hook is set up.

**Comment by benjamin-heasly** [comment]
Hi @DavidBrainard -- I think we've covered these things and moved on.  So I'll close this issue.
