### ISSUE TITLE
Need an ofline mode/utility

### ISSUE THREAD

**Issue by npcottaris** [ToolboxHub/ToolboxToolbox#53]
We should add an offline mode to  tb^2 or at least have a utility that just checks for the the required packages and sets up the paths, and either - 

1. Does not attempt to do any online synchronization, or

2. Attempts to do online synchronization and exits gracefully If there is no internet connectivity.

I understand that this partially eradicates the main idea behind tb^2, but on the other hand it is really frustrating not being able to run your cose when offline.

**Comment by benjamin-heasly** [comment]
Oh no, I thought it *would* proceed when offline.  But it seems that behavior got broken at some point.

Here is a PR that allows deployments to proceed even when offline: #55 .  Could you please try that branch and see if it allows you to keep working offline?

In this PR, it will still print error messages about failed `git pull` and the like.  I will think about how to make that more graceful...

**Comment by benjamin-heasly** [comment]
I added some checks to skip updates of existing toolboxes when offline.  This should suppress errors and give a success status when offline, as long as we are only trying to update toolboxes, and not obtain them in the first place.

How does that work for you?

**Comment by DavidBrainard** [comment]
See comment at end of (now closed) PR 55.  It works as advertised but a few error messages still get printed out as it goes along.

DB
