### ISSUE TITLE
Null path placement

### ISSUE THREAD

**Issue by DavidBrainard** [ToolboxHub/ToolboxToolbox#56]
Although it is hard to imagine wanting to specify a toolbox and not have it on the path, it is easy to imagine wanting to do this for a project.

A little experimentation suggests that entering the empty string in the subfolder field achieves this behavior.  But I think we should make it official, or define some other official way to do this (e.g. entering 'none' in the subfolder field.  

And then add whatever the supported answer is to the documentation as an option, where currently we list "append" and "prepend".

**Comment by benjamin-heasly** [comment]
Cool.

I think `pathPlacement` = `none` feels like a natural way to do this.  I'll make a PR.
