### ISSUE TITLE
Escape characters in .json files?

### ISSUE THREAD

**Issue by DavidBrainard** [ToolboxHub/ToolboxToolbox#6]
On some systems, the .json we create with the Matlab for toolbox registration files has '\/' for each '/', and on some it does not.  I don't know if this matters, but it might be related to some of our woes.  (Although, editing the .json to take out the \ does not help with the problems we're seeing on the Yosemite machine.)

**Comment by benjamin-heasly** [comment]
I don't know if that matters, either.  I wonder which machines produce the escapes and which don't.

I sometimes edit the JSON through the GitHub web interface.  I wonder what happens in that case.

**Comment by benjamin-heasly** [comment]
I added a test for this -- reading the same JSON with and without slash escapes in a url:
  https://github.com/ToolboxHub/ToolboxToolbox/blob/master/test/TbGitAndSanityTest.m#L250

The tests pass both ways.
