### ISSUE TITLE
File system case sensitivity and paths

### ISSUE THREAD

**Issue by gkaguirre** [ToolboxHub/ToolboxToolbox#66]
I have noticed that various toolboxes differ regarding if the `configuration` directory has an initial capital C or not. While this does not matter under HFS+ on the mac (as paths are case insensitive), it does matter on Unix. Specifically, I at some point changed the name of a toolbox configuration directory to begin with a lowercase C, and the tbUse command now failed with the error pasted below.

It is possible that, as TbTb was developed on mac OS, there is ambiguity regarding case in pathnames. It seems that either TbTb should be set to be explicitly case insensitive for mandatory directories (e.g., `project`, `toolbox`, `code`, or `configuration`), or we should settle upon a practice (upper or lower case) and enforce this across toolboxes.

> Creating local hook from template "/home/aguirre/matlab/toolboxes/temporalFittingEngine/Configuration/temporalFittingEngineLocalHookTemplate.m".
> Error using copyfile
> cp: cannot stat
> `/home/aguirre/matlab/toolboxes/temporalFittingEngine/Configuration/temporalFittingEngineLocalHookTemplate.m':
> No such file or directory
> 
> Error in tbDeployToolboxes>invokeLocalHook (line
> 267)
>     copyfile(templatePath, explicitHookPath);
> 
> Error in tbDeployToolboxes (line 168)
>         resolved(tt) =
>         invokeLocalHook(resolved(tt), prefs);
> 
> Error in tbUse (line 32)
> results = tbDeployToolboxes(prefs, 'registered',
> registered);

**Comment by DavidBrainard** [comment]
I think this is an issue with the json file for particular projectd/toolboxes, not the TbTb itself.

In the particular case, the actual project has a directory called "configuration", but in the .json file the location of the template was specified with a path "Configuration/...."  I changed the case in the .json file and pushed to the registry, so I think this should now work on case-sensitive platforms as well as on the Mac.  (I think your basic theory is correct, that case-sensitivity inconsistencies are not well probed on the Mac.)

DB

**Comment by gkaguirre** [comment]
Great, thanks. This case mis-match had gone undetected under HFS+.
