### ISSUE TITLE
How to update registry?

### ISSUE THREAD

**Issue by DavidBrainard** [ToolboxHub/ToolboxToolbox#7]
How should people who don't have access to the ToolboxRegistry upload a new configuration file and/or update an old one.

**Comment by benjamin-heasly** [comment]
I think people should fork the registry repo and make a pull request.  That way we have a chance to review submissions and suggest improvements for functionality and style.

I think we should add a section to the README about this.

**Comment by benjamin-heasly** [comment]
Added notes about contributing for [ToolboxToolbox](https://github.com/ToolboxHub/ToolboxToolbox/blob/master/README.md#contributing) and ToolboxRegistry](https://github.com/ToolboxHub/ToolboxRegistry#toolboxregistry).
