### ISSUE TITLE
Matlab central tools not deployed by toolbox config

### ISSUE THREAD

**Issue by gkaguirre** [ToolboxHub/ToolboxToolbox#70]
When invoked from a project config file, Matlab central repos are properly downloaded, installed, and placed on the path. 

However, when invoked from within a toolbox config from the toolbox registry, the Matlab central entry in the json file appears to be ignored. 

A current example is the temporalFittingEngine and its attempt to place fshift on the path. 

For debugging purposes: be aware that the BrainardLabToolbox contains fshift in its "OneOff" directory, so this can mask the failure of the Matlab central repo to deploy.

**Comment by DavidBrainard** [comment]
I am not able to reproduce this behavior on my machine.

I run tbUse('temporalFittingEngine','reset','full')

and get the following output:

>> tbUse('temporalFittingEngine','reset','full')
Updating "ToolboxRegistry".
Already up-to-date.
Updating "temporalFittingEngine".
Already up-to-date.
Updating "fshift".
Updating "BrainardLabToolbox".
Already up-to-date.
Updating "Psychtoolbox-3".
Already up-to-date.
Updating "UnitTestToolbox".
Already up-to-date.
Updating "RemoteDataToolbox".
Already up-to-date.
Found "jsonlab_v1.2" and skipping update.
Resetting path to factory state.
Adding "ToolboxToolbox" to path at "/Users/dhb/Documents/MATLAB/ToolboxToolbox".
Adding "temporalFittingEngine" to path at "/Users/dhb/Documents/MATLAB/toolboxes/temporalFittingEngine".
Adding "fshift" to path at "/Users/dhb/Documents/MATLAB/toolboxes/matlabcentral/fshift".
Adding "BrainardLabToolbox" to path at "/Users/dhb/Documents/MATLAB/toolboxes/BrainardLabToolbox".
Adding "Psychtoolbox-3" to path at "/Users/dhb/Documents/MATLAB/toolboxes/Psychtoolbox-3/Psychtoolbox".
Adding "UnitTestToolbox" to path at "/Users/dhb/Documents/MATLAB/toolboxes/UnitTestToolbox".
Adding "RemoteDataToolbox" to path at "/Users/dhb/Documents/MATLAB/toolboxes/RemoteDataToolbox".
Adding "jsonlab_v1.2" to path at "/Users/dhb/Documents/MATLAB/toolboxes/jsonlab_v1.2".
Checking for "temporalFittingEngine" local hook.
  Running local hook "/Users/dhb/Documents/MATLAB/localHookFolder/temporalFittingEngine.m".
  Hook success with status 0.
Checking for "fshift" local hook.
Checking for "BrainardLabToolbox" local hook.
Checking for "Psychtoolbox-3" local hook.
Checking for "UnitTestToolbox" local hook.
Checking for "RemoteDataToolbox" local hook.
Checking for "jsonlab_v1.2" local hook.
Looks good: 7 resolved toolboxes deployed OK.

It says that it has put fshift on the path.  And, which fshift -all reveals its presence.

>> which fshift -all
/Users/dhb/Documents/MATLAB/toolboxes/matlabcentral/fshift/fshift.m
/Users/dhb/Documents/MATLAB/toolboxes/BrainardLabToolbox/OneLiners/fshift.m  % Shadowed

The copy in the BrainardLabToolbox is shadowed, as expected from the order in which toolboxes are put onto the path and the fact that later ones are appended.

So I am not sure how to proceed.  TbTb is up to date on the machine you are using?

P.S. I suspect we should take fshift and other matlabcentral stuff out of BLTB and insert explicit entries into the various toolboxRegistry files once we have this issue sorted out.  Or at least put that
on some list of things that would be good to do someday.

**Comment by gkaguirre** [comment]
Thanks for looking at this.

It is strange. Both Harry and I observed the behavior independently. And now, I am unable to reproduce it myself. I'll close this issue unless / until I can reproduce this behavior.

Separately, I very much want to remove Psychtoolbox and the BLTB from the temporal fitting engine. I'll raise this issue elsewhere.
