### ISSUE TITLE
question about local types

### ISSUE THREAD

**Issue by JWinawer** [ToolboxHub/ToolboxToolbox#72]
Hi All, 

We seem to be having a glitch defining a local path for a toolbox registry. I wonder if we have configured out json file incorrectly?

The paths we would like to add are:

/Volumes/server/Projects/MEG/Retinotopy/Code

The way we have written the JSON file is 

[
	{
		"flavor": "",
		"hook": "",
		"importance": "",
		"localHookTemplate": "",
		"name": "Code",
		"pathPlacement": "append",
		"subfolder": "",
		"toolboxRoot": "",
		"type": "local",
		"update": "",
		"url": "file:///Volumes/server/Projects/MEG/Retinotopy/"
	},		
]

The error we get is:

Error using loadjson>error_pos (line 405)
JSONparser:invalidFormat: Value expected at position 270: notopy/"
	},
<error>

Any suggestion would be appreciated.

Thanks,
Jon

**Comment by ragavsathish** [comment]
Hi,
Can you try replacing url as `"url": "file:\/\/\/Volumes\/server\/Projects\/MEG\/Retinotopy\/"`  

I  usually do the following to generate json file as mentioned in [readme](https://github.com/ToolboxHub/ToolboxToolbox#config-in-json)

```Matlab
record = tbToolboxRecord('name', 'Code', 'type', 'local', 'url', 'file:///Volumes/server/Projects/MEG/Retinotopy/');
configPath = fullfile(tempdir(), 'sample-config.json');
tbWriteConfig(record, 'configPath', configPath);
```

**Comment by JWinawer** [comment]
Thanks. That worked.

Jon
