### ISSUE TITLE
TbTb does not work in MATLAB 2012b

### ISSUE THREAD

**Issue by spitschan** [ToolboxHub/ToolboxToolbox#79]
I recently ran into an issue of trying to set up TbTb on a computer running OS X 10.6.8 with MATLAB 2012b, the last supported version for that OS. (I'll spare you the details for why I found myself in that situation.)

Turns out that there are two modern features of `inputParser` which didn't exist or were different back then:

- Partial matching, i.e. the field `PartialMatching` as one sets up the parser object;
- The method `addParameter` was called `addParamValue`.

I've created a branch on my `ToolboxToolbox` fork called `matlab2012b` whose only function is to make TbTb work on that old MATLAB version. It's here: https://github.com/spitschan/ToolboxToolbox/tree/matlab2012b

Not sure if there's a point in adding this branch to the official `ToolboxToolbox` repo on the Toolbox.

**Comment by DavidBrainard** [comment]
I think 2012b is old enough that we don't want to add any official support for it.  But we can try to keep in mind that you have a fix if it ever comes up again.  (In general, I have adopted the view that supporting Matlab 2 years back is about right.)
