### ISSUE TITLE
Basic install help

### ISSUE THREAD

**Issue by gkaguirre** [ToolboxHub/ToolboxToolbox#8]
I'm trying to follow the install instructions and having trouble. I expect I'm making a basic error.

I am working on a Mac with 2014b.

userpath() returns:
/Users/myname/Documents/MATLAB:

Within this directory, I have installed the ToolboxToolbox repo and created a directory named "toolboxes". I have copied the file sampleStartup.m from the tb-tb repo to the top-level of the directory and renamed it to startup.m

When I launch Matlab I receive a string of errors of the type:

> Warning: Name is nonexistent or not a directory: /Users/aguirre/Documents/MATLAB/ToolboxRegistry
> Warning: Name is nonexistent or not a directory: /Users/aguirre/Documents/MATLAB/ToolboxRegistry/.git
> Warning: Name is nonexistent or not a directory: /Users/aguirre/Documents/MATLAB/ToolboxRegistry/.git/hooks
> ...
> Resetting path to factory state.
> Adding "ToolboxToolbox" to path at "/Users/myname/Documents/MATLAB/ToolboxToolbox".

In an attempt to fix this, I uncommented the entire set of lines in the startup.m file under the section "Matlab preferences that control toolbox toolbox". This resolves the initial errors regarding nonexistent directories. However, when I issue the commend tbUse('sample-repo'); I receive this:

> Obtaining "ToolboxRegistry".
> A dot name structure assignment is illegal when the structure is empty.  Use a
> subscript on the structure.
> 
> Error in tbDeployToolboxes (line 145)
> [resolved.path] = deal('');
> 
> Error in tbUse (line 84)
> results = tbDeployToolboxes( ...
 
Thanks for any advice.

Geoff

**Comment by DavidBrainard** [comment]
Andrew Bock and I saw a similar error when calling tbDeployToolboxes in a local hook file when trying to set this up on his laptop (although everything else with that install worked fine until that point).  We ran out of time to track it down.

It might be some Matlab version dependent glitch in the way filenames are constructed and/or the way some edge case (an empty directory) is handled.

I think we’ll need to get Ben to track this down.

I am not sure about the first error you got either, since on other systems I have been able to use the default startup with no modifications.

Bset,

David

**Comment by benjamin-heasly** [comment]
Hi @gkaguirre.

I think we should focus on the first error, first.

I'm confused about `/Users/myname/...` vs `/Users/aguirre/...`.  Are those literally the strings that you're seeing?  Or did you change "aguirre" to "myname" when posting the comment?

Well, if `userpath()` really returns `/Users/myname/...` then it is probably misconfigured.  It should return your actual user name, and not a placeholder like "myname".

You should be able to correct it with a command like this, in Matlab:
```
userpath('/Users/aguirre/Documents/MATLAB');
```

What does `userpath()` return after that?

**Comment by gkaguirre** [comment]
Sorry for the confusion. I changed my actual name to "myname" because of old person Internet privacy fears, not knowing that my git picture and name would be attached to my post!

Today, I upgraded from 2014a to 2016a. I no longer receive the errors that I had found previously. I cannot tell you if the error was Matlab version specific, or if in the upgrade process I fixed something that was previously strange or broken in my configuration. I would lean towards the former, however, as I was happily working under 2014a with good control of my path, startup, and toolboxes.

**Comment by DavidBrainard** [comment]
Ben Chin and Andrew Bock were getting similar errors, so we could check what version of Matlab they are running, and if so maybe try to track down the error before they upgrade.

@Ben and @Andrew, what version of Matlab are you each running, and can you post the specific error messages you are getting.

Best,

David

**Comment by DavidBrainard** [comment]
The trashcan mac has 2015a on it right now. Here's the error message:

>> tbUse('sample-repo');
Obtaining "ToolboxRegistry".
A dot name structure assignment is illegal when the structure is empty.
Use a subscript on the structure.

Error in tbDeployToolboxes (line 145)
[resolved.path] = deal('');

Error in tbUse (line 84)
results = tbDeployToolboxes( ...

**Comment by DavidBrainard** [comment]
On my laptop (MacBook Pro (Retina, 13-inch, Early 2015)) running Matlab
R2014b, I receive the following error message:

>> tbUse('mriTemporalFitting','reset','full');
Updating "ToolboxRegistry".
Updating "BrainardLabToolbox".
Updating "Psychtoolbox-3".
Resetting path to factory state.
Adding "ToolboxToolbox" to path at
"/Users/abock/Documents/MATLAB/ToolboxToolbox".
Adding "BrainardLabToolbox" to path at
"/Users/abock/Documents/MATLAB/toolboxes/BrainardLabToolbox".
Adding "Psychtoolbox-3" to path at
"/Users/abock/Documents/MATLAB/toolboxes/Psychtoolbox-3/Psychtoolbox".
Running local hook for "mriTemporalFitting":
"/Users/abock/Documents/MATLAB/localHookFolder/mriTemporalFitting.m".
Error: "mriTemporalFitting" had status -1, message "A dot name structure
assignment is illegal when the structure is empty.  Use a subscript on the
structure."
Something went wrong, please see above.

**Comment by gkaguirre** [comment]
I'm getting closer, but not there yet. Now on Mac OS X 10.11.6, with Matlab 2016a. I have the sample startup.m file installed in my user path. User path returns:

> /Users/aguirre/Documents/MATLAB:

My MATLAB directory looks like this:

![screen shot 2016-09-12 at 3 34 59 pm](https://cloud.githubusercontent.com/assets/10457908/18449790/949863e2-78fe-11e6-88f3-6d128c8a4d93.png)

When I start Matlab I get this:

> Resetting path to factory state.
> Adding "ToolboxToolbox" to path at "/Users/aguirre/Documents/MATLAB/ToolboxToolbox".

But, when I try to use the sample-repo, I get this:

> >> tbUse('sample-repo');
> which master.txt
> Obtaining "ToolboxRegistry".
> Adding "ToolboxToolbox" to path at "/Users/aguirre/Documents/MATLAB/ToolboxToolbox".
> Looks good: all toolboxes deployed OK.
> 'master.txt' not found.
>

**Comment by gkaguirre** [comment]
Mystery solved. I did not have home-brew / command line git tools installed, as I have been using the Tower interface.

Manuel Spitschan gave me a hand with this and will post a separate issue regarding TbTb message behavior in this circumstance.

**Comment by spitschan** [comment]
Issue #9 opened for this purpose.
