### ISSUE TITLE
MATLAB calls to `git` should check that the `git` command can be executed successfully

### ISSUE THREAD

**Issue by spitschan** [ToolboxHub/ToolboxToolbox#9]
In trying to debug issue 8 (https://github.com/ToolboxHub/ToolboxToolbox/issues/8), we discovered that even when the `git` command exists in the terminal path and on the MATLAB path, deployment with TbTb does not work properly. The following error then is thrown in the terminal and/or as the second output of the `system` call in MATLAB, which reads:

```
xcrun: error: invalid active developer path
 (/Library/Developer/CommandLineTools), missing xcrun at:
 /Library/Developer/CommandLineTools/usr/bin/xcrun
```

We fixed this by making sure that `git` works in the command line. In this case, we just installed git again from homebrew.

**Comment by spitschan** [comment]
Perhaps one way to approach this would to run

```
outcome = system('git --version')
```

and throw and error if `outcome ~= 0`.

**Comment by benjamin-heasly** [comment]
OK, that makes sense.  I think OS X starts with a phoney version of some commands like git, so it will exist in some sense but not behave like git.

So I like your suggestion of checking for the git version.
