### ISSUE TITLE
Speedup tbUse()

### ISSUE THREAD

**Issue by githubkusi** [ToolboxHub/ToolboxToolbox#90]
I'd like to use tbUse() at the beginning of my script to set the correct path. However, currently this is too slow. Running tbUse('sample-repo') takes 3.8s 

The most expensive calls are
![image](https://user-images.githubusercontent.com/5463044/51242085-6787ba00-197f-11e9-8a3a-0fba3ff25509.png)

* Can I tell tbUse() not to update neither TbTb nor the TbRegistry? 
* Currently, a toolbox is always updated, could that be made optional, even if update != "never"? (no git calls to the server)
* It turns out that 'reset'='full' is very slow (1.4s), compared to 'reset'=''as-is' (0.1s)

**Comment by DavidBrainard** [comment]
Handled via PR #91.  See discussion there.  Closing.
